name: kadai4-actions
on: push
jobs:
  kadai4-pattern-check:
    name: kadai4-pattern-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo 'Test for kadai4'
      - run: pwd
      - run: sh /gha_test.sh